# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-10 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0007_auto_20180827_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='legal_words',
            field=models.CharField(blank=True, max_length=250, verbose_name='Название специальности, для проверки совпадений'),
        ),
    ]
