# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-20 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='token',
            field=models.UUIDField(blank=True, default='75c08e22-c493-48a0-a444-8852daa6a79d'),
            preserve_default=False,
        ),
    ]
