# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-20 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0002_subscriber_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
